default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: conventional-commits
        name: Conventional commits
        entry: .githooks/commit-msg
        language: script
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      # ruff-check --fix must run before ruff-format
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.12
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright src/
        language: system
        pass_filenames: false
        types: [python]

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
